services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks: [appnet]

  app:
    build:
      context: ./docker/php
    volumes:
      - ./src:/var/www/html:delegated
      - app_writable:/var/www/html/storage
      - app_writable:/var/www/html/bootstrap/cache
    depends_on:
      - db
      - redis
      - mailpit
    networks: [appnet]

  worker:
    build:
      context: ./docker/php
    command: ["php", "artisan", "queue:work", "--sleep=1", "--tries=3", "--timeout=90"]
    volumes:
      - ./src:/var/www/html:delegated
      - app_writable:/var/www/html/storage
      - app_writable:/var/www/html/bootstrap/cache
    depends_on:
      - app
      - redis
      - mailpit
    networks: [appnet]

  scheduler:
    build:
      context: ./docker/php
    command: ["sh", "-lc", "while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"]
    volumes:
      - ./src:/var/www/html:delegated
      - app_writable:/var/www/html/storage
      - app_writable:/var/www/html/bootstrap/cache
    depends_on:
      - app
      - db
      - redis
      - mailpit
    networks: [appnet]

  db:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "33060:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks: [appnet]

  redis:
    image: redis:7-alpine
    ports:
      - "63790:6379"
    networks: [appnet]

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
    networks: [appnet]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootsecret
    depends_on:
      - db
    networks: [appnet]

  node:
    image: node:20-alpine
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_HOST=0.0.0.0
      - VITE_PORT=5173
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"

networks:
  appnet:

volumes:
  dbdata:
  app_writable:
